/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __create = Object.create;
var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __getProtoOf = Object.getPrototypeOf;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __commonJS = (cb, mod) => function __require() {
  return mod || (0, cb[__getOwnPropNames(cb)[0]])((mod = { exports: {} }).exports, mod), mod.exports;
};
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toESM = (mod, isNodeMode, target) => (target = mod != null ? __create(__getProtoOf(mod)) : {}, __copyProps(
  // If the importer is in node compatibility mode or this is not an ESM
  // file that has been converted to a CommonJS file using a Babel-
  // compatible transform (i.e. "__esModule" has not been set), then set
  // "default" to the CommonJS "module.exports" for node compatibility.
  isNodeMode || !mod || !mod.__esModule ? __defProp(target, "default", { value: mod, enumerable: true }) : target,
  mod
));
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// node_modules/dotenv/package.json
var require_package = __commonJS({
  "node_modules/dotenv/package.json"(exports, module2) {
    module2.exports = {
      name: "dotenv",
      version: "16.4.5",
      description: "Loads environment variables from .env file",
      main: "lib/main.js",
      types: "lib/main.d.ts",
      exports: {
        ".": {
          types: "./lib/main.d.ts",
          require: "./lib/main.js",
          default: "./lib/main.js"
        },
        "./config": "./config.js",
        "./config.js": "./config.js",
        "./lib/env-options": "./lib/env-options.js",
        "./lib/env-options.js": "./lib/env-options.js",
        "./lib/cli-options": "./lib/cli-options.js",
        "./lib/cli-options.js": "./lib/cli-options.js",
        "./package.json": "./package.json"
      },
      scripts: {
        "dts-check": "tsc --project tests/types/tsconfig.json",
        lint: "standard",
        "lint-readme": "standard-markdown",
        pretest: "npm run lint && npm run dts-check",
        test: "tap tests/*.js --100 -Rspec",
        "test:coverage": "tap --coverage-report=lcov",
        prerelease: "npm test",
        release: "standard-version"
      },
      repository: {
        type: "git",
        url: "git://github.com/motdotla/dotenv.git"
      },
      funding: "https://dotenvx.com",
      keywords: [
        "dotenv",
        "env",
        ".env",
        "environment",
        "variables",
        "config",
        "settings"
      ],
      readmeFilename: "README.md",
      license: "BSD-2-Clause",
      devDependencies: {
        "@definitelytyped/dtslint": "^0.0.133",
        "@types/node": "^18.11.3",
        decache: "^4.6.1",
        sinon: "^14.0.1",
        standard: "^17.0.0",
        "standard-markdown": "^7.1.0",
        "standard-version": "^9.5.0",
        tap: "^16.3.0",
        tar: "^6.1.11",
        typescript: "^4.8.4"
      },
      engines: {
        node: ">=12"
      },
      browser: {
        fs: false
      }
    };
  }
});

// node_modules/dotenv/lib/main.js
var require_main = __commonJS({
  "node_modules/dotenv/lib/main.js"(exports, module2) {
    var fs = require("fs");
    var path = require("path");
    var os = require("os");
    var crypto = require("crypto");
    var packageJson = require_package();
    var version = packageJson.version;
    var LINE = /(?:^|^)\s*(?:export\s+)?([\w.-]+)(?:\s*=\s*?|:\s+?)(\s*'(?:\\'|[^'])*'|\s*"(?:\\"|[^"])*"|\s*`(?:\\`|[^`])*`|[^#\r\n]+)?\s*(?:#.*)?(?:$|$)/mg;
    function parse(src) {
      const obj = {};
      let lines = src.toString();
      lines = lines.replace(/\r\n?/mg, "\n");
      let match;
      while ((match = LINE.exec(lines)) != null) {
        const key = match[1];
        let value = match[2] || "";
        value = value.trim();
        const maybeQuote = value[0];
        value = value.replace(/^(['"`])([\s\S]*)\1$/mg, "$2");
        if (maybeQuote === '"') {
          value = value.replace(/\\n/g, "\n");
          value = value.replace(/\\r/g, "\r");
        }
        obj[key] = value;
      }
      return obj;
    }
    function _parseVault(options) {
      const vaultPath = _vaultPath(options);
      const result = DotenvModule.configDotenv({ path: vaultPath });
      if (!result.parsed) {
        const err = new Error(`MISSING_DATA: Cannot parse ${vaultPath} for an unknown reason`);
        err.code = "MISSING_DATA";
        throw err;
      }
      const keys = _dotenvKey(options).split(",");
      const length = keys.length;
      let decrypted;
      for (let i = 0; i < length; i++) {
        try {
          const key = keys[i].trim();
          const attrs = _instructions(result, key);
          decrypted = DotenvModule.decrypt(attrs.ciphertext, attrs.key);
          break;
        } catch (error) {
          if (i + 1 >= length) {
            throw error;
          }
        }
      }
      return DotenvModule.parse(decrypted);
    }
    function _log(message) {
      console.log(`[dotenv@${version}][INFO] ${message}`);
    }
    function _warn(message) {
      console.log(`[dotenv@${version}][WARN] ${message}`);
    }
    function _debug(message) {
      console.log(`[dotenv@${version}][DEBUG] ${message}`);
    }
    function _dotenvKey(options) {
      if (options && options.DOTENV_KEY && options.DOTENV_KEY.length > 0) {
        return options.DOTENV_KEY;
      }
      if (process.env.DOTENV_KEY && process.env.DOTENV_KEY.length > 0) {
        return process.env.DOTENV_KEY;
      }
      return "";
    }
    function _instructions(result, dotenvKey) {
      let uri;
      try {
        uri = new URL(dotenvKey);
      } catch (error) {
        if (error.code === "ERR_INVALID_URL") {
          const err = new Error("INVALID_DOTENV_KEY: Wrong format. Must be in valid uri format like dotenv://:key_1234@dotenvx.com/vault/.env.vault?environment=development");
          err.code = "INVALID_DOTENV_KEY";
          throw err;
        }
        throw error;
      }
      const key = uri.password;
      if (!key) {
        const err = new Error("INVALID_DOTENV_KEY: Missing key part");
        err.code = "INVALID_DOTENV_KEY";
        throw err;
      }
      const environment = uri.searchParams.get("environment");
      if (!environment) {
        const err = new Error("INVALID_DOTENV_KEY: Missing environment part");
        err.code = "INVALID_DOTENV_KEY";
        throw err;
      }
      const environmentKey = `DOTENV_VAULT_${environment.toUpperCase()}`;
      const ciphertext = result.parsed[environmentKey];
      if (!ciphertext) {
        const err = new Error(`NOT_FOUND_DOTENV_ENVIRONMENT: Cannot locate environment ${environmentKey} in your .env.vault file.`);
        err.code = "NOT_FOUND_DOTENV_ENVIRONMENT";
        throw err;
      }
      return { ciphertext, key };
    }
    function _vaultPath(options) {
      let possibleVaultPath = null;
      if (options && options.path && options.path.length > 0) {
        if (Array.isArray(options.path)) {
          for (const filepath of options.path) {
            if (fs.existsSync(filepath)) {
              possibleVaultPath = filepath.endsWith(".vault") ? filepath : `${filepath}.vault`;
            }
          }
        } else {
          possibleVaultPath = options.path.endsWith(".vault") ? options.path : `${options.path}.vault`;
        }
      } else {
        possibleVaultPath = path.resolve(process.cwd(), ".env.vault");
      }
      if (fs.existsSync(possibleVaultPath)) {
        return possibleVaultPath;
      }
      return null;
    }
    function _resolveHome(envPath) {
      return envPath[0] === "~" ? path.join(os.homedir(), envPath.slice(1)) : envPath;
    }
    function _configVault(options) {
      _log("Loading env from encrypted .env.vault");
      const parsed = DotenvModule._parseVault(options);
      let processEnv = process.env;
      if (options && options.processEnv != null) {
        processEnv = options.processEnv;
      }
      DotenvModule.populate(processEnv, parsed, options);
      return { parsed };
    }
    function configDotenv(options) {
      const dotenvPath = path.resolve(process.cwd(), ".env");
      let encoding = "utf8";
      const debug = Boolean(options && options.debug);
      if (options && options.encoding) {
        encoding = options.encoding;
      } else {
        if (debug) {
          _debug("No encoding is specified. UTF-8 is used by default");
        }
      }
      let optionPaths = [dotenvPath];
      if (options && options.path) {
        if (!Array.isArray(options.path)) {
          optionPaths = [_resolveHome(options.path)];
        } else {
          optionPaths = [];
          for (const filepath of options.path) {
            optionPaths.push(_resolveHome(filepath));
          }
        }
      }
      let lastError;
      const parsedAll = {};
      for (const path2 of optionPaths) {
        try {
          const parsed = DotenvModule.parse(fs.readFileSync(path2, { encoding }));
          DotenvModule.populate(parsedAll, parsed, options);
        } catch (e) {
          if (debug) {
            _debug(`Failed to load ${path2} ${e.message}`);
          }
          lastError = e;
        }
      }
      let processEnv = process.env;
      if (options && options.processEnv != null) {
        processEnv = options.processEnv;
      }
      DotenvModule.populate(processEnv, parsedAll, options);
      if (lastError) {
        return { parsed: parsedAll, error: lastError };
      } else {
        return { parsed: parsedAll };
      }
    }
    function config2(options) {
      if (_dotenvKey(options).length === 0) {
        return DotenvModule.configDotenv(options);
      }
      const vaultPath = _vaultPath(options);
      if (!vaultPath) {
        _warn(`You set DOTENV_KEY but you are missing a .env.vault file at ${vaultPath}. Did you forget to build it?`);
        return DotenvModule.configDotenv(options);
      }
      return DotenvModule._configVault(options);
    }
    function decrypt(encrypted, keyStr) {
      const key = Buffer.from(keyStr.slice(-64), "hex");
      let ciphertext = Buffer.from(encrypted, "base64");
      const nonce = ciphertext.subarray(0, 12);
      const authTag = ciphertext.subarray(-16);
      ciphertext = ciphertext.subarray(12, -16);
      try {
        const aesgcm = crypto.createDecipheriv("aes-256-gcm", key, nonce);
        aesgcm.setAuthTag(authTag);
        return `${aesgcm.update(ciphertext)}${aesgcm.final()}`;
      } catch (error) {
        const isRange = error instanceof RangeError;
        const invalidKeyLength = error.message === "Invalid key length";
        const decryptionFailed = error.message === "Unsupported state or unable to authenticate data";
        if (isRange || invalidKeyLength) {
          const err = new Error("INVALID_DOTENV_KEY: It must be 64 characters long (or more)");
          err.code = "INVALID_DOTENV_KEY";
          throw err;
        } else if (decryptionFailed) {
          const err = new Error("DECRYPTION_FAILED: Please check your DOTENV_KEY");
          err.code = "DECRYPTION_FAILED";
          throw err;
        } else {
          throw error;
        }
      }
    }
    function populate(processEnv, parsed, options = {}) {
      const debug = Boolean(options && options.debug);
      const override = Boolean(options && options.override);
      if (typeof parsed !== "object") {
        const err = new Error("OBJECT_REQUIRED: Please check the processEnv argument being passed to populate");
        err.code = "OBJECT_REQUIRED";
        throw err;
      }
      for (const key of Object.keys(parsed)) {
        if (Object.prototype.hasOwnProperty.call(processEnv, key)) {
          if (override === true) {
            processEnv[key] = parsed[key];
          }
          if (debug) {
            if (override === true) {
              _debug(`"${key}" is already defined and WAS overwritten`);
            } else {
              _debug(`"${key}" is already defined and was NOT overwritten`);
            }
          }
        } else {
          processEnv[key] = parsed[key];
        }
      }
    }
    var DotenvModule = {
      configDotenv,
      _configVault,
      _parseVault,
      config: config2,
      decrypt,
      parse,
      populate
    };
    module2.exports.configDotenv = DotenvModule.configDotenv;
    module2.exports._configVault = DotenvModule._configVault;
    module2.exports._parseVault = DotenvModule._parseVault;
    module2.exports.config = DotenvModule.config;
    module2.exports.decrypt = DotenvModule.decrypt;
    module2.exports.parse = DotenvModule.parse;
    module2.exports.populate = DotenvModule.populate;
    module2.exports = DotenvModule;
  }
});

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => ClickUpPlugin
});
module.exports = __toCommonJS(main_exports);

// src/components/CreateTaskModal.ts
var import_obsidian3 = require("obsidian");

// src/utils/UiUtils.ts
var createFolder = ({
  folder,
  vault
}) => {
  try {
    vault.createFolder(folder);
  } catch (e) {
    console.log(`Folder ${folder} already exists`);
  }
};
var createTable = (rows) => {
  if (!rows.length) {
    return "No tasks found";
  }
  const headers = Object.keys(rows[0]);
  let tableHTML = "| ";
  headers.forEach((header) => {
    tableHTML += `${header} | `;
  });
  tableHTML += "\n|";
  headers.forEach(() => {
    tableHTML += " --- |";
  });
  tableHTML += "\n";
  rows.forEach((row) => {
    tableHTML += "| ";
    headers.forEach((header) => {
      const value = Array.isArray(row[header]) ? row[header].join(", ") : row[header];
      tableHTML += `${value} | `;
    });
    tableHTML += "\n";
  });
  return tableHTML;
};
var createInputWithPlaceholder = (label, placeholder, required = false, type = "input") => {
  const element = type === "textarea" ? document.createElement("textarea") : document.createElement("input");
  element.placeholder = placeholder;
  element.classList.add("createInputWithPlaceholder");
  if (type === "textarea") {
    element.classList.add("largeInput");
  }
  const labelElement = document.createElement("label");
  labelElement.textContent = label;
  labelElement.classList.add("input-label");
  if (required) {
    element.classList.add("required");
    labelElement.classList.add("required-label");
  }
  return { element, label: labelElement };
};
var createSelectWithOptions = (options, placeholder = "", required = false) => {
  const element = document.createElement("select");
  element.classList.add("createSelectWithOptions");
  const labelElement = document.createElement("label");
  labelElement.textContent = placeholder;
  labelElement.classList.add("select-label");
  if (required) {
    element.classList.add("required");
    labelElement.classList.add("required-label");
  }
  options.forEach((option) => {
    const optionElement = document.createElement("option");
    optionElement.value = String(option.value);
    optionElement.text = option.text;
    element.appendChild(optionElement);
  });
  return { element, label: labelElement };
};
var applyStylesToContainer = (container, component) => {
  container.classList.add("input-container", "applyStylesToContainer");
  container.appendChild(component.label);
  container.appendChild(component.element);
};
var getElementValue = (component) => {
  return component.element.value;
};
var validateForm = (container) => {
  const requiredInputs = container.querySelectorAll(".required");
  let isValid = true;
  requiredInputs.forEach((input) => {
    if (!input.value) {
      isValid = false;
    }
  });
  return isValid;
};

// src/components/constants.ts
var firstListOption = {
  text: "Lists",
  value: ""
};
var firstAssigneeOption = {
  text: "Assignees",
  value: ""
};
var prioritySelectOptions = [
  { value: "", text: "Priorities" },
  { value: 1, text: "Urgent" },
  { value: 2, text: "High" },
  { value: 3, text: "Normal" },
  { value: 4, text: "Low" }
];
var SIGNIN_STEPS = [
  '1. Click Sign-in button, it redirects to your ClickUp account. Login your ClickUp account and select workspace, click "Connect Workspace" button',
  '2. Copy code and click "Open obsidian" button.',
  "3. Paste copied code to input located in Sign-in modal in below:"
];

// src/services/ApiService.ts
var import_obsidian = require("obsidian");
var ApiService = class {
  constructor() {
  }
  static getInstance() {
    if (!ApiService.instance) {
      ApiService.instance = new ApiService();
    }
    return ApiService.instance;
  }
  async fetcher(url, options = {}) {
    console.log({ url: `https://api.clickup.com/api/v2/${url}` });
    const token = localStorage.getItem("click_up_token");
    const request = (0, import_obsidian.requestUrl)({
      contentType: "application/json",
      url: `https://api.clickup.com/api/v2/${url}`,
      headers: {
        Authorization: token,
        "Grant Type": "Authorization Code"
      },
      method: options.method,
      body: options.body,
      throw: true
    });
    return request;
  }
  async getToken(code) {
    if (!code)
      return "MISSING_CODE";
    console.log({ code });
    const CLICK_UP_CLIENT = "TGKZSPVNT4Z5VWFN4PG5YC8WK9BCJ5YX";
    const CLICK_UP_SECRET = "NJ00S013WRCPBU9AJL1H2M8RX4C7LTSCN7KXZ2RJT60UPJNX3YRDC0MCUN48Q53B";
    const query = new URLSearchParams({
      client_id: CLICK_UP_CLIENT,
      client_secret: CLICK_UP_SECRET,
      code
    }).toString();
    try {
      const resp = await this.fetcher(`oauth/token?${query}`, {
        method: "POST"
      });
      let responseBody = null;
      try {
        responseBody = await resp.json;
      } catch (jsonErr) {
        console.error("Failed to parse JSON response", jsonErr);
      }
      const data = responseBody;
      localStorage.setItem("click_up_token", data.access_token);
      return data.access_token;
    } catch (error) {
      console.error("Error during getToken()", error);
      return void 0;
    }
  }
  async getAuthorizedUser() {
    const resp = await this.fetcher(`user`);
    const data = await resp.json;
    return data.user;
  }
  async getTeams() {
    const resp = await this.fetcher(`team`);
    const data = await resp.json;
    return data.teams;
  }
  async getSpaces(team_id) {
    const response = await this.fetcher(`team/${team_id}/space`);
    const data = await response.json;
    return data.spaces;
  }
  async getFolders(space_id) {
    const response = await this.fetcher(`space/${space_id}/folder`);
    const data = await response.json;
    return data.folders;
  }
  async getList(folder_id) {
    const response = await this.fetcher(`folder/${folder_id}/list`);
    const data = await response.json;
    return data.lists;
  }
  async getFolderlessList(space_id) {
    const response = await this.fetcher(`space/${space_id}/list`);
    const data = await response.json;
    return data.lists;
  }
  async getTasks(list_id) {
    const response = await this.fetcher(`list/${list_id}/task`);
    const data = await response.json;
    return data.tasks;
  }
  async getClickupLists(folderId) {
    const response = await this.fetcher(`folder/${folderId}/list`);
    const data = await response.json;
    return data.lists;
  }
  async getWorkspaceUser(teamId, userId) {
    const response = await this.fetcher(`team/${teamId}/user/${userId}`);
    const data = await response.json;
    return data;
  }
  async getAllFolders(space_id) {
    const response = await this.fetcher(`space/${space_id}/folder`);
    const data = await response.json;
    return data.folders;
  }
  async getListMembers(list_id) {
    const response = await this.fetcher(`list/${list_id}/member`);
    const data = await response.json;
    return data.members;
  }
  async createTask({
    listId,
    data
  }) {
    const response = await this.fetcher(`list/${listId}/task`, {
      method: "POST",
      body: JSON.stringify(data),
      headers: {
        "Content-Type": "application/json"
      }
    });
    const responseData = await response.json;
    return responseData;
  }
  async showError(e) {
    console.log(e);
    if (e.message.includes("Oauth token not found")) {
      new import_obsidian.Notice(
        "Error related to authorization, please re-login",
        1e4
      );
      console.log("Error related to authorization, please re-login");
      return { isAuth: false, message: "no auth" };
    } else {
      new import_obsidian.Notice(`Error: ${e.message}`, 5e3);
      return { isAuth: true, message: e.message };
    }
  }
};

// src/services/AuthService.ts
var AuthService = class {
  constructor() {
    this.apiService = ApiService.getInstance();
  }
  static getInstance() {
    if (!AuthService.instance) {
      AuthService.instance = new AuthService();
    }
    return AuthService.instance;
  }
  /**
   * Authenticates with ClickUp using the provided code
   */
  async authenticate(code) {
    return await this.apiService.getToken(code);
  }
  /**
   * Gets the authenticated user
   */
  async getAuthenticatedUser() {
    return await this.apiService.getAuthorizedUser();
  }
  /**
   * Fetches teams for the authenticated user
   */
  async getTeams() {
    return await this.apiService.getTeams();
  }
  /**
   * Checks if user is authenticated
   */
  isAuthenticated() {
    return Boolean(localStorage.getItem("click_up_token"));
  }
  /**
   * Logs the user out
   */
  logout() {
    localStorage.removeItem("lists");
    localStorage.removeItem("selectedList");
    localStorage.removeItem("click_up_token");
    localStorage.removeItem("selectedSpace");
  }
  /**
   * Loads all spaces for all teams
   */
  async loadAllSpaces(teams) {
    const spaces = [];
    for (const team of teams) {
      const teamSpaces = await this.apiService.getSpaces(team.id);
      teamSpaces.forEach(
        (sp) => spaces.push({ name: sp.name, id: sp.id })
      );
    }
    return spaces;
  }
  /**
   * Loads all lists for all spaces in all teams
   */
  async loadAllLists(teams) {
    const lists = [];
    for (const team of teams) {
      const spaces = await this.apiService.getSpaces(team.id);
      for (const space of spaces) {
        const folders = await this.apiService.getAllFolders(space.id);
        for (const folder of folders || []) {
          const folderLists = await this.apiService.getList(folder.id) || [];
          folderLists.forEach(
            (list) => lists.push({ name: list.name, id: list.id })
          );
        }
        const folderlessLists = await this.apiService.getFolderlessList(space.id) || [];
        folderlessLists.forEach(
          (list) => lists.push({ name: list.name, id: list.id })
        );
      }
    }
    return lists;
  }
  /**
   * Stores lists in local storage
   */
  async configureListsLocally(teams) {
    const lists = await this.loadAllLists(teams);
    localStorage.setItem("lists", JSON.stringify(lists));
  }
};

// src/services/StorageService.ts
var StorageService = class {
  constructor() {
  }
  static getInstance() {
    if (!StorageService.instance) {
      StorageService.instance = new StorageService();
    }
    return StorageService.instance;
  }
  // Token related methods
  getToken() {
    return localStorage.getItem("click_up_token");
  }
  setToken(token) {
    localStorage.setItem("click_up_token", token);
  }
  removeToken() {
    localStorage.removeItem("click_up_token");
  }
  // Code related methods
  setCode(code) {
    localStorage.setItem("CLICK_UP_CODE", code);
  }
  getCode() {
    return localStorage.getItem("CLICK_UP_CODE");
  }
  // List related methods
  setLists(lists) {
    localStorage.setItem("lists", JSON.stringify(lists));
  }
  getLists() {
    const lists = localStorage.getItem("lists");
    return lists ? JSON.parse(lists) : [];
  }
  setSelectedList(list) {
    localStorage.setItem("selectedList", JSON.stringify(list));
  }
  getSelectedList() {
    const selectedList = localStorage.getItem("selectedList");
    return selectedList ? JSON.parse(selectedList) : null;
  }
  // Space related methods
  setSelectedSpace(space) {
    localStorage.setItem("selectedSpace", JSON.stringify(space));
  }
  getSelectedSpace() {
    const selectedSpace = localStorage.getItem("selectedSpace");
    return selectedSpace ? JSON.parse(selectedSpace) : null;
  }
  // Clear all data
  clearAllData() {
    localStorage.removeItem("lists");
    localStorage.removeItem("selectedList");
    localStorage.removeItem("click_up_token");
    localStorage.removeItem("selectedSpace");
    localStorage.removeItem("CLICK_UP_CODE");
  }
};

// src/services/TaskService.ts
var import_obsidian2 = require("obsidian");
var TaskService = class {
  constructor() {
    this.apiService = ApiService.getInstance();
  }
  static getInstance() {
    if (!TaskService.instance) {
      TaskService.instance = new TaskService();
    }
    return TaskService.instance;
  }
  /**
   * Creates a new task in the specified list
   */
  async createTask(listId, taskData) {
    try {
      const task = await this.apiService.createTask({
        data: taskData,
        listId
      });
      if (task.err) {
        console.log(task);
        throw new Error(task.err);
      }
      new import_obsidian2.Notice("Created new task!", 3e3);
      return task;
    } catch (err) {
      const errorResponse = await this.apiService.showError(err);
      return { error: errorResponse, success: false };
    }
  }
  /**
   * Creates a task from the selected text in the editor
   */
  async createTaskFromSelection(selection, listId) {
    const requestData = {
      name: selection,
      description: "",
      assignees: [],
      priority: 3
    };
    try {
      const task = await this.apiService.createTask({
        data: requestData,
        listId
      });
      if (task.err) {
        throw new Error(task.err);
      }
      return task;
    } catch (err) {
      const errorResponse = await this.apiService.showError(err);
      return { error: errorResponse, success: false };
    }
  }
  /**
   * Gets tasks from a list
   */
  async getTasks(listId) {
    try {
      return await this.apiService.getTasks(listId);
    } catch (err) {
      const errorResponse = await this.apiService.showError(err);
      return { error: errorResponse, success: false };
    }
  }
  /**
   * Format task data for table display
   */
  formatTasksForTable(tasks) {
    return tasks.map((task, index) => {
      var _a, _b;
      return {
        order: index + 1,
        name: task.name,
        status: task.status.status,
        date_created: new Date(
          Number(task.date_created)
        ).toLocaleString("en-US"),
        creator: task.creator.username,
        assignees: task.assignees.map((u) => u.username),
        priority: (_b = (_a = task == null ? void 0 : task.priority) == null ? void 0 : _a.priority) != null ? _b : "Low"
      };
    });
  }
};

// src/components/CreateTaskModal.ts
var CreateTaskModal = class extends import_obsidian3.Modal {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
    this.apiService = ApiService.getInstance();
    this.authService = AuthService.getInstance();
    this.taskService = TaskService.getInstance();
    this.configureListsLocally();
  }
  async loadLists() {
    const { teams } = this.plugin.settings;
    return await this.authService.loadAllLists(teams);
  }
  async configureListsLocally() {
    const { teams } = this.plugin.settings;
    await this.authService.configureListsLocally(teams);
  }
  async onOpen() {
    const { contentEl } = this;
    let listSelects = null;
    const loading = contentEl.createEl("h3", { text: "Loading..." });
    try {
      const lists = await this.loadLists();
      listSelects = lists.map((item) => ({
        text: item.name,
        value: item.id
      }));
      contentEl.removeChild(loading);
    } catch (error) {
      loading.textContent = "Something went wrong";
    }
    if (!listSelects) {
      return;
    }
    let listMember = [];
    const listSelectOptions = [firstListOption, ...listSelects];
    const container = document.createElement("div");
    container.classList.add("task-modal-container");
    const title = document.createElement("h2");
    title.textContent = "Create task";
    title.classList.add("task-modal-title");
    container.appendChild(title);
    const listSelect = createSelectWithOptions(
      listSelectOptions,
      "Select list",
      true
    );
    listSelect.element.classList.add("createSelectWithOptions");
    const assigneeSelectOptions = [firstAssigneeOption, ...listMember];
    listSelect.element.addEventListener("change", async () => {
      const members = await this.apiService.getListMembers(
        listSelect.element.value
      );
      listMember = members.map((member) => ({
        ...member,
        value: member.id,
        text: member.username
      }));
      assigneeSelectOptions.length = 0;
      assigneeSelectOptions.push(...[...listMember]);
      assigneeSelectOptions.map(
        (option) => assigneeSelect.element.createEl("option", {
          value: String(option.value),
          text: option.text
        })
      );
    });
    const assigneeSelect = createSelectWithOptions(
      //@ts-ignore
      assigneeSelectOptions,
      "Select assignee",
      true
    );
    const prioritySelect = createSelectWithOptions(
      prioritySelectOptions,
      "Select priority",
      true
    );
    const titleInput = createInputWithPlaceholder(
      "Title",
      "Enter title",
      true
    );
    const descriptionInput = createInputWithPlaceholder(
      "Description",
      "Enter description",
      true,
      "textarea"
    );
    const containerChilds = [
      listSelect,
      titleInput,
      descriptionInput,
      assigneeSelect,
      prioritySelect
    ];
    containerChilds.forEach((child) => {
      const wrapperDiv = document.createElement("div");
      wrapperDiv.classList.add("input-container");
      applyStylesToContainer(wrapperDiv, child);
      container.appendChild(wrapperDiv);
      container.appendChild(document.createElement("br"));
    });
    const submitButton = document.createElement("button");
    submitButton.textContent = "Add";
    submitButton.classList.add("submit-btn");
    const errorMessage = container.createEl("p", {
      cls: "error-message",
      text: "Please fill in all required fields!"
    });
    errorMessage.toggleClass("errorMessageHide", true);
    submitButton.addEventListener("click", () => {
      console.clear();
      if (validateForm(container)) {
        errorMessage.toggleClass("errorMessageHide", true);
        this.handleFormSubmit(
          {
            title: getElementValue(titleInput),
            assignee: getElementValue(assigneeSelect),
            description: getElementValue(descriptionInput),
            list: getElementValue(listSelect),
            priority: getElementValue(prioritySelect)
          },
          submitButton
        );
      } else {
        errorMessage.toggleClass("errorMessageHide", false);
      }
    });
    const submitContainer = container.createEl("div", {
      cls: "submit-container"
    });
    submitContainer.classList.add("submitContainer");
    submitContainer.appendChild(submitButton);
    container.appendChild(submitContainer);
    contentEl.appendChild(container);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  async handleFormSubmit(data, btn) {
    const { assignee, description, list, priority, title } = data;
    btn.textContent = "Loading...";
    btn.disabled = true;
    const requestData = {
      name: title,
      description,
      assignees: [Number(assignee)],
      priority: Number(priority)
    };
    try {
      const result = await this.taskService.createTask(list, requestData);
      if (result.error) {
        throw new Error(result.error.message);
      }
      btn.textContent = "Success";
      btn.toggleClass("createTaskSucces", true);
      this.close();
      this.plugin.syncronizeListNote(list);
    } catch (error) {
      console.log(error);
      btn.textContent = "Error";
      btn.toggleClass("createTaskError", true);
    } finally {
      btn.disabled = false;
    }
  }
};

// src/main.ts
var import_obsidian7 = require("obsidian");

// src/signIn.ts
var import_obsidian4 = require("obsidian");
var MainAppModal = class extends import_obsidian4.Modal {
  constructor(plugin) {
    super(plugin.app);
    this.plugin = plugin;
    this.authService = AuthService.getInstance();
    this.storageService = StorageService.getInstance();
    this.renderAuthorization();
  }
  async loadSpaces() {
    const { teams } = this.plugin.settings;
    return await this.authService.loadAllSpaces(teams);
  }
  async configureListsLocally() {
    const { teams } = this.plugin.settings;
    await this.authService.configureListsLocally(teams);
  }
  async loadLists() {
    const { teams } = this.plugin.settings;
    return await this.authService.loadAllLists(teams);
  }
  renderAuthorization() {
    const { contentEl } = this;
    contentEl.empty();
    const plugin = this.plugin;
    const container = document.createElement("div");
    container.classList.add("signin-container");
    const title = document.createElement("h1");
    title.classList.add("signin-title");
    const description = document.createElement("p");
    description.classList.add("signin-description");
    const button = document.createElement("button");
    button.classList.add("signBtn");
    const steps = document.createElement("div");
    steps.classList.add("signin-steps");
    const input = createInputWithPlaceholder("Code", "Enter code", true);
    input.element.classList.add("createInputWithPlaceholder");
    SIGNIN_STEPS.forEach((stepItem) => {
      const step = document.createElement("p");
      step.textContent = stepItem;
      step.classList.add("signin-step");
      steps.appendChild(step);
    });
    title.textContent = "Click Up sync";
    description.textContent = "We need to retrieve authorization token from ClickUp to start synchronizing your tasks from Obsidian notes";
    button.textContent = "Sign In";
    button.addEventListener("click", async () => {
      const inputValue = input.element.value;
      if (!inputValue) {
        window.open(
          "https://app.clickup.com/api?client_id=TGKZSPVNT4Z5VWFN4PG5YC8WK9BCJ5YX&redirect_uri=https://clickup.dedicated.agency/obsidian",
          "_blank"
        );
      }
      let token;
      if (inputValue) {
        button.disabled = true;
        button.textContent = "Loading...";
        button.classList.add("renderAuthrizationBtn");
        token = await this.authService.authenticate(inputValue);
        if (token) {
          await plugin.fetchUser(token);
          button.toggleClass("renderAuthrizationBtnSucces", true);
          button.textContent = "Success";
          new import_obsidian4.Notice("Success", 3e3);
          this.plugin.settingsTab.renderSettings();
          this.close();
        }
      }
    });
    steps.appendChild(input.element);
    container.appendChild(title);
    container.appendChild(description);
    container.appendChild(steps);
    container.appendChild(button);
    contentEl.appendChild(container);
  }
  async addDefaultListSelectionEl(wrapper) {
    const selectedList = this.storageService.getSelectedList();
    const selectThisListContent = document.createElement("p");
    selectThisListContent.classList.add("list-selection-label");
    const disabledOption = document.createElement("option");
    const listSelect = document.createElement("select");
    listSelect.classList.add("createSelectWithOptions", "largeSelect");
    selectThisListContent.textContent = "Select default list";
    disabledOption.textContent = "Loading..";
    disabledOption.selected = true;
    disabledOption.disabled = true;
    listSelect.appendChild(disabledOption);
    setTimeout(async () => {
      const lists = await this.loadLists() || [];
      disabledOption.textContent = "Lists";
      lists.forEach(async (list) => {
        const option = document.createElement("option");
        option.textContent = list.name;
        option.id = list.id;
        listSelect.appendChild(option);
      });
      if (selectedList) {
        listSelect.value = selectedList.name;
      }
    }, 1);
    listSelect.addEventListener("change", () => {
      const id = listSelect.options[listSelect.selectedIndex].id;
      this.storageService.setSelectedList({
        name: listSelect.value,
        id
      });
    });
    const container = document.createElement("div");
    container.appendChild(selectThisListContent);
    container.appendChild(listSelect);
    container.classList.add("addDefaultListSelectionEl-container");
    wrapper.appendChild(container);
  }
  async addSpacesSelectionEl(wrapper) {
    const selectedSpace = this.storageService.getSelectedSpace();
    const selectThisListContent = document.createElement("p");
    selectThisListContent.classList.add("space-selection-label");
    const disabledOption = document.createElement("option");
    const listSelect = document.createElement("select");
    listSelect.classList.add("createSelectWithOptions", "largeSelect");
    selectThisListContent.textContent = "Select workspace";
    disabledOption.textContent = "Loading...";
    disabledOption.selected = true;
    disabledOption.disabled = true;
    listSelect.appendChild(disabledOption);
    setTimeout(async () => {
      const spaces = await this.loadSpaces();
      disabledOption.textContent = "Spaces";
      spaces.forEach(async (space) => {
        const option = document.createElement("option");
        option.textContent = space.name;
        option.id = space.id;
        listSelect.appendChild(option);
      });
      if (selectedSpace) {
        listSelect.value = selectedSpace.name;
      }
    }, 100);
    listSelect.addEventListener("change", () => {
      const id = listSelect.options[listSelect.selectedIndex].id;
      this.storageService.setSelectedSpace({
        name: listSelect.value,
        id
      });
    });
    const container = document.createElement("div");
    container.appendChild(selectThisListContent);
    container.appendChild(listSelect);
    container.classList.add("addDefaultListSelectionEl-container");
    wrapper.appendChild(container);
  }
};

// src/components/SigninRequired.ts
var import_obsidian5 = require("obsidian");
var SigninRequiredModal = class extends import_obsidian5.Modal {
  constructor(app, plugin) {
    super(app);
    this.plugin = plugin;
  }
  onOpen() {
    const { contentEl } = this;
    const container = document.createElement("div");
    container.classList.add("signin-required-container");
    const title = document.createElement("h2");
    title.textContent = "Please Sign-in to create task";
    title.classList.add("signin-title");
    const content = document.createElement("p");
    content.textContent = "Please first click on the desired icon on the sidebar and register.";
    content.classList.add("signin-text");
    contentEl.appendChild(container);
    container.appendChild(title);
    container.appendChild(content);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/settings.ts
var import_obsidian6 = require("obsidian");
var ClickUpSettingTab = class extends import_obsidian6.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
    this.apiService = ApiService.getInstance();
    this.authService = AuthService.getInstance();
    this.storageService = StorageService.getInstance();
    this.taskService = TaskService.getInstance();
  }
  async loadSpaces() {
    const { teams } = this.plugin.settings;
    return await this.authService.loadAllSpaces(teams);
  }
  async loadLists() {
    const { teams } = this.plugin.settings;
    return await this.authService.loadAllLists(teams);
  }
  async configureListsLocally() {
    const { teams } = this.plugin.settings;
    await this.authService.configureListsLocally(teams);
  }
  renderSettings() {
    var _a, _b, _c;
    let { containerEl } = this;
    const { teams } = this.plugin.settings;
    containerEl.empty();
    new import_obsidian6.Setting(containerEl).setName("Select space").addDropdown(async (dropdown) => {
      dropdown.setDisabled(true);
      try {
        const spaces = await this.loadSpaces();
        const selectedSpace = this.storageService.getSelectedSpace();
        spaces.forEach((space) => {
          dropdown.addOption(JSON.stringify(space), space.name);
        });
        if (selectedSpace) {
          dropdown.setValue(JSON.stringify(selectedSpace));
        }
        dropdown.onChange((value) => {
          this.storageService.setSelectedSpace(JSON.parse(value));
        });
        dropdown.setDisabled(false);
      } catch (error) {
        const errorResponse = await this.apiService.showError(
          error
        );
        if (!errorResponse.isAuth) {
          this.plugin.logOut();
        }
        dropdown.disabled = true;
        this.renderSignIn();
        dropdown.addOption("", "error");
      }
    });
    new import_obsidian6.Setting(containerEl).setName("Select default sheet").addDropdown(async (dropdown) => {
      dropdown.setDisabled(true);
      try {
        const lists = await this.loadLists();
        const selectedList = this.storageService.getSelectedList();
        lists.forEach((list) => {
          dropdown.addOption(list.id.toString(), list.name);
        });
        if (selectedList) {
          dropdown.setValue(selectedList.id);
        }
        dropdown.onChange((value) => {
          var _a2;
          const selectedListName = ((_a2 = lists.find((l) => l.id === value)) == null ? void 0 : _a2.name) || "";
          this.storageService.setSelectedList({
            name: selectedListName,
            id: value
          });
        });
        dropdown.setDisabled(false);
      } catch (error) {
        const errorResponse = await this.apiService.showError(
          error
        );
        if (!errorResponse.isAuth) {
          this.plugin.logOut();
        }
        this.renderSignIn();
        dropdown.disabled = true;
        dropdown.addOption("", "error");
      }
    }).setDesc("");
    new import_obsidian6.Setting(containerEl).setName(`WorkSpaces: ${(_a = teams[0]) == null ? void 0 : _a.name}`).setDesc(
      `Members:[${(_b = teams[0]) == null ? void 0 : _b.members.map(
        (member) => `${member.user.username},`
      )}]`
    ).addButton((btn) => {
      btn.setButtonText("sync");
      btn.buttonEl.classList.add("sync-button");
      btn.onClick(async () => {
        new import_obsidian6.Notice(`Loading...`, 3e3);
        btn.buttonEl.classList.add("forceSyncBtn");
        await this.configureListsLocally();
        createFolder({ folder: `ClickUp`, vault: this.app.vault });
        for (const team of teams) {
          createFolder({
            folder: `ClickUp/${team.name}`,
            vault: this.app.vault
          });
          const spaces = await this.apiService.getSpaces(team.id);
          for (const space of spaces) {
            createFolder({
              folder: `ClickUp/${team.name}/${space.name} - [${space.id}]`,
              vault: this.app.vault
            });
            const folders = await this.apiService.getFolders(
              space.id
            );
            for (const folder of folders || []) {
              createFolder({
                folder: `ClickUp/${team.name}/${space.name} - [${space.id}]/${folder.name}`,
                vault: this.app.vault
              });
            }
            const folderlesLists = await this.apiService.getFolderlessList(
              space.id
            );
            for (const list of folderlesLists) {
              const vault = this.plugin.app.vault;
              const tasks = await this.apiService.getTasks(
                list.id
              );
              const rows = this.taskService.formatTasksForTable(tasks);
              const tableHTML = createTable(rows);
              const filePath = `/ClickUp/${team.name}/${space.name} - [${space.id}]/${list.name}[${list.id}].md`;
              try {
                vault.create(filePath, tableHTML);
              } catch (err) {
                if (err.message === "File already exists.") {
                  const files = vault.getMarkdownFiles();
                  for (let i = 0; i < files.length; i++) {
                    const element = files[i];
                    if (element.name === `${list.name}[${list.id}].md`) {
                      vault.delete(element);
                      vault.create(
                        filePath,
                        tableHTML
                      );
                      new import_obsidian6.Notice(
                        `Successfully updated ${list.name}`,
                        3e3
                      );
                    }
                  }
                } else {
                  console.error(err);
                }
              }
            }
          }
        }
        btn.buttonEl.classList.remove("forceSyncBtn");
      });
    });
    new import_obsidian6.Setting(containerEl).setName(
      "User: " + (((_c = this.plugin.settings.user) == null ? void 0 : _c.username) || "doesnt registration")
    ).addButton((btn) => {
      btn.setButtonText("Log out");
      btn.buttonEl.classList.add("logout-button");
      btn.onClick(async () => {
        this.plugin.logOut();
      });
    });
  }
  renderSignIn() {
    let { containerEl } = this;
    containerEl.empty();
    const signInContainer = containerEl.createEl("div", {
      cls: "signin-container"
    });
    new import_obsidian6.Setting(signInContainer).setName("Sign In").addButton((button) => {
      button.setButtonText("Sign In");
      button.buttonEl.classList.add("signBtn");
      button.onClick(async () => {
        this.plugin.modal.open();
      });
    });
  }
  async display() {
    if (this.authService.isAuthenticated()) {
      this.renderSettings();
    } else {
      this.renderSignIn();
    }
  }
};

// src/interfaces/PluginSettings.ts
var DEFAULT_SETTINGS = {
  user: null,
  teamId: "",
  teams: [],
  token: ""
};

// src/main.ts
var dotenv = __toESM(require_main());
dotenv.config({
  debug: false
});
var ClickUpPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    this.apiService = ApiService.getInstance();
    this.authService = AuthService.getInstance();
    this.storageService = StorageService.getInstance();
    this.taskService = TaskService.getInstance();
    this.settingsTab = new ClickUpSettingTab(this.app, this);
    this.addSettingTab(this.settingsTab);
    this.registerObsidianProtocolHandler("ClickUpPlugin", async (e) => {
      const parameters = e;
      this.storageService.setCode(parameters.code);
    });
    await this.loadSettings();
    this.modal = new MainAppModal(this);
    if (!this.authService.isAuthenticated()) {
      this.logOut();
    } else {
      this.saveSettings();
      this.settingsTab.renderSettings();
      this.fetchUser(JSON.stringify(this.storageService.getToken()));
    }
    this.addCommand({
      id: "manual-create-task-clickUp",
      name: "Create ClickUp task",
      // hotkeys: [{ modifiers: ["Ctrl", "Shift"], key: "c" }],
      callback: async () => {
        if (!this.authService.isAuthenticated()) {
          new SigninRequiredModal(this.app, this).open();
        } else {
          new CreateTaskModal(this).open();
        }
      }
    });
    this.addCommand({
      id: "create-task-clickUp-selection",
      name: "Create ClickUp task from selection",
      editorCallback: async (editor, view) => {
        const sel = editor.getSelection();
        const defaultList = this.storageService.getSelectedList();
        if (!sel) {
          return;
        }
        if (!defaultList) {
          new import_obsidian7.Notice("Please select a sheet in settings");
          return;
        }
        try {
          const task = await this.taskService.createTaskFromSelection(
            sel,
            defaultList.id
          );
          if (!task.error) {
            setTimeout(() => {
              editor.replaceRange(
                ` [task](${task.url})`,
                editor.getCursor("to")
              );
              new import_obsidian7.Notice("Created new task!", 3e3);
            }, 100);
          } else if (!task.error.isAuth) {
            this.logOut();
          }
        } catch (err) {
          const errorResponse = await this.apiService.showError(err);
          if (!errorResponse.isAuth) {
            this.logOut();
          }
        }
      }
    });
  }
  async logOut() {
    this.clearUser();
    this.settingsTab.renderSignIn();
  }
  async fetchUser(token) {
    const user = await this.apiService.getAuthorizedUser();
    const teams = await this.apiService.getTeams();
    await this.saveData({ user, token, teams });
    await this.loadSettings();
  }
  async clearUser() {
    this.storageService.clearAllData();
    await this.saveData({ token: null, user: null, teams: [] });
  }
  async loadSettings() {
    this.settings = Object.assign(
      {},
      DEFAULT_SETTINGS,
      await this.loadData()
    );
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  async syncronizeListNote(id) {
    const note = this.app.vault.getFiles().filter((f) => f.path.startsWith("ClickUp")).find((f) => f.path.includes(`[${id}]`));
    if (!note) {
      console.log("could not find note to sync");
      return;
    }
    const vault = this.app.vault;
    const tasks = await this.apiService.getTasks(id);
    const rows = this.taskService.formatTasksForTable(tasks);
    const tableHTML = createTable(rows);
    const filePath = note.path.toString();
    vault.delete(note);
    try {
      vault.create(filePath, tableHTML);
      new import_obsidian7.Notice("List synchronized successfully", 3e3);
    } catch (error) {
      console.error("Failed to synchronize list", error);
      new import_obsidian7.Notice("Failed to synchronize list", 3e3);
    }
  }
};

/* nosourcemap */